#!/usr/bin/env bash
# Generates lib/blur-map.ts — a tiny LQIP for every local image.
#
# next/image only produces blur placeholders automatically for *statically
# imported* images. Ours are referenced by path from content data, so without
# this every photograph pops in cold.
#
# These are 5x4 PNGs, which next/image scales up and CSS-blurs. A JPEG at this
# size is ~1.6KB because the header dominates; a PNG is around 150 bytes for
# the same visual result, and these get inlined into the HTML of every page
# that renders the image, so the difference is worth having.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="lib/blur-map.ts"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

{
  echo "/**"
  echo " * Low-quality image placeholders, generated by scripts/build-blur.sh."
  echo " *"
  echo " * Do not edit by hand. Re-run after adding an image:"
  echo " *   ./scripts/build-blur.sh"
  echo " */"
  echo "export const BLUR_MAP: Record<string, string> = {"
} > "$OUT"

count=0
while IFS= read -r f; do
  key="${f#public}"
  magick "$f" -resize 5x4\! -strip "PNG8:$TMP/t.png" 2>/dev/null
  b64=$(base64 -i "$TMP/t.png" | tr -d '\n')
  echo "  \"$key\": \"data:image/png;base64,$b64\"," >> "$OUT"
  count=$((count+1))
done < <(find public/images -name '*.jpg' | sort)

echo "};" >> "$OUT"
echo "generated $count placeholders -> $OUT"
